// <auto-generated />
namespace Wivuu.DataSeed.Tests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbseed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbseed));
        
        string IMigrationMetadata.Id
        {
            get { return "201508120332181_db seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
